### ISSUE TITLE
cannot find examples/echo.cpp

### ISSUE THREAD

**Issue by bigben0123** [Manoharan-Ajay-Anand/coros#1]
Hi,
I cannot find your example files:
https://github.com/Manoharan-Ajay-Anand/coros/blob/main/examples/echo.cpp

**Comment by Manoharan-Ajay-Anand** [comment]
I am sorry. I moved them here: [https://github.com/Manoharan-Ajay-Anand/coros-framework/blob/main/examples/echo.cpp]( https://github.com/Manoharan-Ajay-Anand/coros-framework/blob/main/examples/echo.cpp).
